using DictionaryAPI.Data;

namespace DictionaryAPI.Services
{
    public class DatabaseSeeder
    {
        private readonly DictionaryContext _context;

        public DatabaseSeeder(DictionaryContext context)
        {
            _context = context;
        }

        // Method to seed data
        public void SeedTranslations()
        {
            if (_context.Dictionary.Any()) return; // Skip seeding if data already exists

            // Manually add English-Hungarian translations
            var translations = new List<DictionaryEntry>
            {
                new DictionaryEntry { EnglishWord = "Account Holder Name", HungarianTranslation = "Számlatulajdonos neve" },
                new DictionaryEntry { EnglishWord = "Accounting and Finance", HungarianTranslation = "Pénzügy" },
                new DictionaryEntry { EnglishWord = "Active", HungarianTranslation = "Aktív" },
                new DictionaryEntry { EnglishWord = "Add New Fee", HungarianTranslation = "Új díj létrehozása" },
                new DictionaryEntry { EnglishWord = "Add new Comment", HungarianTranslation = "Új megjegyzés létrehozása" },
                new DictionaryEntry { EnglishWord = "Add new entry", HungarianTranslation = "Új bejegyzés" },
                new DictionaryEntry { EnglishWord = "Add New Vendor", HungarianTranslation = "Új szolgáltató létrehozása" },
                new DictionaryEntry { EnglishWord = "Additional Editor Assignments", HungarianTranslation = "Minőségellenőrzési megjegyzések" },
                new DictionaryEntry { EnglishWord = "Management", HungarianTranslation = "Minőségellenőrzési megjegyzések" },
                new DictionaryEntry { EnglishWord = "Administration", HungarianTranslation = "Adminisztráció" },
                new DictionaryEntry { EnglishWord = "Advertisement payment handling", HungarianTranslation = "Hirdetési kifizetések kezelése" },
                new DictionaryEntry { EnglishWord = "Agency", HungarianTranslation = "Ügynökség" },
                new DictionaryEntry { EnglishWord = "Alipay Account", HungarianTranslation = "Alipay fiók" },
                new DictionaryEntry { EnglishWord = "Analysis", HungarianTranslation = "Analízis" },
                new DictionaryEntry { EnglishWord = "Announcements", HungarianTranslation = "Közlemények" },
                new DictionaryEntry { EnglishWord = "Annual closing", HungarianTranslation = "Éves zárás" },
                new DictionaryEntry { EnglishWord = "tax return and audit", HungarianTranslation = "adóbevallás és ellenőrzés" },
                new DictionaryEntry { EnglishWord = "Annual Review Feedback", HungarianTranslation = "Teljesítményértékelés" },
                new DictionaryEntry { EnglishWord = "Apollo Manager Id - Data Quality", HungarianTranslation = "Apollo Manager Id - Data Quality" },
                new DictionaryEntry { EnglishWord = "Apollo Manager Id - Resource", HungarianTranslation = "Apollo Manager Id - Resource" },
                new DictionaryEntry { EnglishWord = "Applying payments in Caspian", HungarianTranslation = "Bejövő fizetések könyvelése" },
                new DictionaryEntry { EnglishWord = "AR follow up", HungarianTranslation = "Kintlévőségkezelés" },
                new DictionaryEntry { EnglishWord = "Automated report", HungarianTranslation = "Automatizált riport" },
                new DictionaryEntry { EnglishWord = "Bamboo", HungarianTranslation = "Bamboo" },
                new DictionaryEntry { EnglishWord = "Bank Account Number", HungarianTranslation = "Számlaszám" },
                new DictionaryEntry { EnglishWord = "Bank Address", HungarianTranslation = "Bank cím" },
                new DictionaryEntry { EnglishWord = "Bank Name", HungarianTranslation = "Bank név" },
                new DictionaryEntry { EnglishWord = "BI - Assist other department", HungarianTranslation = "BI - más osztályok támogatása" },
                new DictionaryEntry { EnglishWord = "BI - Assistance other offices", HungarianTranslation = "BI - más irodák támogatása" },
                new DictionaryEntry { EnglishWord = "BI - Design, Illustrations, Graphic layout, CSS", HungarianTranslation = "BI - Design, Illustrations, Graphic layout, CSS" },
                new DictionaryEntry { EnglishWord = "BI - Development solutions files", HungarianTranslation = "BI - Development solutions files" },
                new DictionaryEntry { EnglishWord = "BI - Specific analysis (Tier, Route, Cost, etc.)", HungarianTranslation = "BI - Különleges elemzések (Tier, Route, Cost, etc.)" },
                new DictionaryEntry { EnglishWord = "Billing", HungarianTranslation = "Számlázás" },
                new DictionaryEntry { EnglishWord = "BR support", HungarianTranslation = "BR támogatás" },
                new DictionaryEntry { EnglishWord = "Branch Name / Id", HungarianTranslation = "Fióknév / Id" },
                new DictionaryEntry { EnglishWord = "Bravo Jobe", HungarianTranslation = "Bravo jogok" },
                new DictionaryEntry { EnglishWord = "Bravo User", HungarianTranslation = "Bravo felhasználó" },
                new DictionaryEntry { EnglishWord = "Budget preparation", HungarianTranslation = "Költségvetés készítés" },
                new DictionaryEntry { EnglishWord = "Business management", HungarianTranslation = "Üzletmenet" },
                new DictionaryEntry { EnglishWord = "Calling new Shoppers", HungarianTranslation = "Új próbavásárlók hívása" },
                new DictionaryEntry { EnglishWord = "Calls - Shoppers", HungarianTranslation = "Hívás - Próbavásárló" },
                new DictionaryEntry { EnglishWord = "Calls", HungarianTranslation = "Hívás" },
                new DictionaryEntry { EnglishWord = "meetings - Client, SM", HungarianTranslation = "megbeszélés - Ügyfél, SM" },
                new DictionaryEntry { EnglishWord = "meetings - Internal", HungarianTranslation = "megbeszélés - belső" },
                new DictionaryEntry { EnglishWord = "Calls Advertisement Providers", HungarianTranslation = "Hirdetési szolgáltatók hívása" },
                new DictionaryEntry { EnglishWord = "Calls Emails", HungarianTranslation = "Calls Emails" },
                new DictionaryEntry { EnglishWord = "Cancel", HungarianTranslation = "Visszavon" },
                new DictionaryEntry { EnglishWord = "Cash Forecast", HungarianTranslation = "Pénzügyi előrejelzés" },
                new DictionaryEntry { EnglishWord = "Caspian", HungarianTranslation = "Caspian" },
                new DictionaryEntry { EnglishWord = "Caspian (entering, managing leads)", HungarianTranslation = "Caspian (Lead kezelés, létrehozás)" },
                new DictionaryEntry { EnglishWord = "Caspian Office Users", HungarianTranslation = "Caspian Felhasználók" },
                new DictionaryEntry { EnglishWord = "Caspian Primary User", HungarianTranslation = "Elsődleges Caspian felhasználó" },
                new DictionaryEntry { EnglishWord = "Caspian Roles", HungarianTranslation = "Caspian jogok" },
                new DictionaryEntry { EnglishWord = "Change Requests", HungarianTranslation = "Változási kérelem" },
                new DictionaryEntry { EnglishWord = "Choose one...", HungarianTranslation = "Válassz..." },
                new DictionaryEntry { EnglishWord = "CL support", HungarianTranslation = "CL támogatás" },
                new DictionaryEntry { EnglishWord = "Client", HungarianTranslation = "Ügyfél" },
                new DictionaryEntry { EnglishWord = "Client Agreement Creation & Follow-up", HungarianTranslation = "Ügyfélszerződés létrehozása és nyomon követése" },
                new DictionaryEntry { EnglishWord = "Client communication", HungarianTranslation = "Ügyfél kommunikáció" },
                new DictionaryEntry { EnglishWord = "Client Excel reporting", HungarianTranslation = "Ügyfél Excel Riportálás" },
                new DictionaryEntry { EnglishWord = "Client related communication", HungarianTranslation = "Ügyfél kapcsolattartás" },
                new DictionaryEntry { EnglishWord = "Client Reporting", HungarianTranslation = "Ügyfél Riportálás" },
                new DictionaryEntry { EnglishWord = "Client", HungarianTranslation = "Ügyfél" },
                new DictionaryEntry { EnglishWord = "Prospect – follow up", HungarianTranslation = "Kapcsolat utánkövetés" },
                new DictionaryEntry { EnglishWord = "Prospect meeting", HungarianTranslation = "Kapcsolat megbeszélés" },
                new DictionaryEntry { EnglishWord = "CN support", HungarianTranslation = "CN támogatás" },
                new DictionaryEntry { EnglishWord = "Cold Calls", HungarianTranslation = "Hideghívás" },
                new DictionaryEntry { EnglishWord = "Comment", HungarianTranslation = "Megjegyzés" },
                new DictionaryEntry { EnglishWord = "Comments", HungarianTranslation = "Megjegyzések" },
                new DictionaryEntry { EnglishWord = "Company Name", HungarianTranslation = "Cégnév" },
                new DictionaryEntry { EnglishWord = "Contract Expires", HungarianTranslation = "Szerződés lejárat" },
                new DictionaryEntry { EnglishWord = "Contract Expiry Date", HungarianTranslation = "Szerződés lejárati ideje" },
                new DictionaryEntry { EnglishWord = "Copy", HungarianTranslation = "Másol" },
                new DictionaryEntry { EnglishWord = "Cost-out, RFP", HungarianTranslation = "Ajánlatkészítés" },
                new DictionaryEntry { EnglishWord = "Country Codes...", HungarianTranslation = "Országkódok..." },
                new DictionaryEntry { EnglishWord = "Create New Vendor", HungarianTranslation = "Új szolgáltató létrehozása" },
                new DictionaryEntry { EnglishWord = "Created", HungarianTranslation = "Létrehozva" },
                new DictionaryEntry { EnglishWord = "Creating client proposal", HungarianTranslation = "Ügyfélajánlat létrehozása" },
                new DictionaryEntry { EnglishWord = "Creating Process", HungarianTranslation = "Folyamat létrehozása" },
                new DictionaryEntry { EnglishWord = "Procedures", HungarianTranslation = "Folyamat létrehozása" },
                new DictionaryEntry { EnglishWord = "Credit memos entering", HungarianTranslation = "Jóváíró számla létrehozása" },
                new DictionaryEntry { EnglishWord = "approving", HungarianTranslation = "kezelés" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - BI", HungarianTranslation = "Osztályközi támogatás - BI" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - DQ", HungarianTranslation = "Osztályközi támogatás - DQ" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - Finance", HungarianTranslation = "Osztályközi támogatás - Pénzügy" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - HR", HungarianTranslation = "Osztályközi támogatás - HR" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - IT", HungarianTranslation = "Osztályközi támogatás - IT" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - KAM", HungarianTranslation = "Osztályközi támogatás - KAM" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - MKTG", HungarianTranslation = "Osztályközi támogatás - MKTG" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - RM", HungarianTranslation = "Osztályközi támogatás - RM" },
                new DictionaryEntry { EnglishWord = "Cross Departmental Support - Sales", HungarianTranslation = "Osztályközi támogatás - Sales" },
                new DictionaryEntry { EnglishWord = "Currency", HungarianTranslation = "Pénznem" },
                new DictionaryEntry { EnglishWord = "Data Checking in Excel", HungarianTranslation = "Adatellenőrzés Excelben" },
                new DictionaryEntry { EnglishWord = "Data cleaning, checking and matching", HungarianTranslation = "Adattisztítás, ellenőrzés és összekötés" },
                new DictionaryEntry { EnglishWord = "Date", HungarianTranslation = "Dátum" },
                new DictionaryEntry { EnglishWord = "Delete", HungarianTranslation = "Törlés" },
                new DictionaryEntry { EnglishWord = "Department", HungarianTranslation = "Osztály" },
                new DictionaryEntry { EnglishWord = "DQ Supervisor", HungarianTranslation = "DQ Csoportvezető" },
                new DictionaryEntry { EnglishWord = "Edit", HungarianTranslation = "Módosít" },
                new DictionaryEntry { EnglishWord = "Edit Timesheet Entry", HungarianTranslation = "Jelenléti ív módosítása" },
                new DictionaryEntry { EnglishWord = "Editing reports (First Line Editing)", HungarianTranslation = "Minőségellenőrzés (1. szintű)" },
                new DictionaryEntry { EnglishWord = "Editor Assignments", HungarianTranslation = "Editor megbízások" },
                new DictionaryEntry { EnglishWord = "Editor Invoicing", HungarianTranslation = "Editor számlázás" },
                new DictionaryEntry { EnglishWord = "Email", HungarianTranslation = "E-mail" },
                new DictionaryEntry { EnglishWord = "E-mail", HungarianTranslation = "E-mail" },
                new DictionaryEntry { EnglishWord = "Employee Attendance Control", HungarianTranslation = "Munkavállalói részvétel ellenőrzése" },
                new DictionaryEntry { EnglishWord = "Employee Benefits payment", HungarianTranslation = "Munkavállalói juttatások kifizetése" },
                new DictionaryEntry { EnglishWord = "Employee Feedback", HungarianTranslation = "Munkavállalói visszajelzések" },
                new DictionaryEntry { EnglishWord = "End", HungarianTranslation = "Vége" },
                new DictionaryEntry { EnglishWord = "End date:", HungarianTranslation = "Vég dátum:" },
                new DictionaryEntry { EnglishWord = "End time:", HungarianTranslation = "Vég idő:" },
                new DictionaryEntry { EnglishWord = "Entering Data in Accounting software", HungarianTranslation = "Adatok bevitele a Számviteli rendszerbe" },
                new DictionaryEntry { EnglishWord = "Entry overlaps with an existing entry:", HungarianTranslation = "A bejegyzés átfedésben van egy meglévő bejegyzéssel:" },
                new DictionaryEntry { EnglishWord = "EU support", HungarianTranslation = "EU támogatás" },
                new DictionaryEntry { EnglishWord = "Export", HungarianTranslation = "Export" },
                new DictionaryEntry { EnglishWord = "Fee", HungarianTranslation = "Díj" },
                new DictionaryEntry { EnglishWord = "Fee Type", HungarianTranslation = "Díj típus" },
                new DictionaryEntry { EnglishWord = "Fees", HungarianTranslation = "Díjak" },
                new DictionaryEntry { EnglishWord = "Fieldwork Partner", HungarianTranslation = "Fieldwork Partner" },
                new DictionaryEntry { EnglishWord = "First Name", HungarianTranslation = "Keresztnév" },
                new DictionaryEntry { EnglishWord = "Follow up", HungarianTranslation = "Utánkövetés" },
                new DictionaryEntry { EnglishWord = "Friday", HungarianTranslation = "Péntek" },
                new DictionaryEntry { EnglishWord = "Full Tier", HungarianTranslation = "Full Tier" },
                new DictionaryEntry { EnglishWord = "Global Anti-Fraud Group Work", HungarianTranslation = "Csalásellenes Vizsgálat" },
                new DictionaryEntry { EnglishWord = "Global support", HungarianTranslation = "Global támogatás" },
                new DictionaryEntry { EnglishWord = "Health Care Assistance", HungarianTranslation = "Egészségügyi segítségnyújtás" },
                new DictionaryEntry { EnglishWord = "Hide New Comment", HungarianTranslation = "Új megjegyzés elrejtése" },
                new DictionaryEntry { EnglishWord = "Hiring", HungarianTranslation = "Felvétel" },
                new DictionaryEntry { EnglishWord = "Interview", HungarianTranslation = "interjú" },
                new DictionaryEntry { EnglishWord = "Onboarding Process", HungarianTranslation = "Beléptetési folyamat" },
                new DictionaryEntry { EnglishWord = "Hold-A Management", HungarianTranslation = "Hold-A Kezelés" },
                new DictionaryEntry { EnglishWord = "Hold-B Management", HungarianTranslation = "Hold-B Kezelés" },
                new DictionaryEntry { EnglishWord = "Home", HungarianTranslation = "Főoldal" },
                new DictionaryEntry { EnglishWord = "IBAN Code", HungarianTranslation = "IBAN Kód" },
                new DictionaryEntry { EnglishWord = "Bank Account Number", HungarianTranslation = "Számlaszám" },
                new DictionaryEntry { EnglishWord = "Id", HungarianTranslation = "Azonosító" },
                new DictionaryEntry { EnglishWord = "IN support", HungarianTranslation = "IN támogatás" },
                new DictionaryEntry { EnglishWord = "Independent User", HungarianTranslation = "Önálló felhasználó" },
                new DictionaryEntry { EnglishWord = "Internal communication", HungarianTranslation = "Belső kommunikáció" },
                new DictionaryEntry { EnglishWord = "Internal queries", HungarianTranslation = "Belső megkeresések" },
                new DictionaryEntry { EnglishWord = "Internal reporting", HungarianTranslation = "Belső riportálás" },
                new DictionaryEntry { EnglishWord = "Interoffice communication", HungarianTranslation = "Irodaközi kommunikáció" },
                new DictionaryEntry { EnglishWord = "Invoicing", HungarianTranslation = "Számlázás" },
                new DictionaryEntry { EnglishWord = "Io communication", HungarianTranslation = "Irodaközi kommunikáció" },
                new DictionaryEntry { EnglishWord = "Is Fieldwork Partner", HungarianTranslation = "Fieldwork Partner?" },
                new DictionaryEntry { EnglishWord = "IsAgency?", HungarianTranslation = "Ügynökség?" },
                new DictionaryEntry { EnglishWord = "IT_Admin Tasks", HungarianTranslation = "IT_admin feladatok" },
                new DictionaryEntry { EnglishWord = "KAM Supervisor", HungarianTranslation = "KAM csoportvezető" },
                new DictionaryEntry { EnglishWord = "KPI calculation", HungarianTranslation = "KPI számítás" },
                new DictionaryEntry { EnglishWord = "Last login", HungarianTranslation = "Utolsó belépés" },
                new DictionaryEntry { EnglishWord = "Last Name", HungarianTranslation = "Vezetéknév" },
                new DictionaryEntry { EnglishWord = "Lead Research", HungarianTranslation = "Lead keresés" },
                new DictionaryEntry { EnglishWord = "List the sheet entries", HungarianTranslation = "Jelenléti ív tételeinek listázása" },
                new DictionaryEntry { EnglishWord = "List timesheet entries", HungarianTranslation = "Jelenléti ív tételeinek listázása" },
                new DictionaryEntry { EnglishWord = "Logout", HungarianTranslation = "Kijelentkezés" },
                new DictionaryEntry { EnglishWord = "Managing Contractors, Vendors", HungarianTranslation = "Szolgáltatók kezelése" },
                new DictionaryEntry { EnglishWord = "Material creation", HungarianTranslation = "Szakmai anyagok létrehozása" },
                new DictionaryEntry { EnglishWord = "Modified", HungarianTranslation = "Módosítva" },
                new DictionaryEntry { EnglishWord = "Monday", HungarianTranslation = "Hétfő" },
                new DictionaryEntry { EnglishWord = "More", HungarianTranslation = "Több" },
                new DictionaryEntry { EnglishWord = "Name", HungarianTranslation = "Név" },
                new DictionaryEntry { EnglishWord = "Networking Events", HungarianTranslation = "Kapcsolatépítési események" },
                new DictionaryEntry { EnglishWord = "New Hire - Training", HungarianTranslation = "Újbelépő tréning" },
                new DictionaryEntry { EnglishWord = "New Timesheet Entry", HungarianTranslation = "Új jelenléti ív tétel létrehozása" },
                new DictionaryEntry { EnglishWord = "Next", HungarianTranslation = "Következő" },
                new DictionaryEntry { EnglishWord = "No", HungarianTranslation = "Nem" },
                new DictionaryEntry { EnglishWord = "Office", HungarianTranslation = "Iroda" },
                new DictionaryEntry { EnglishWord = "Office Management", HungarianTranslation = "Iroda kezelés" },
                new DictionaryEntry { EnglishWord = "Official Jobtitle", HungarianTranslation = "Hivatalos Munkakör" },
                new DictionaryEntry { EnglishWord = "OH and attributes calculation", HungarianTranslation = "OH és attribútum számítás" },
                new DictionaryEntry { EnglishWord = "Opt Fee is only applied if the starting status is Reviewed.", HungarianTranslation = "Az opciós díjat csak akkor alkalmazzák, ha a kiindulási státusz Reviewed." },
                new DictionaryEntry { EnglishWord = "Opt. Fee", HungarianTranslation = "Opt. díj" },
                new DictionaryEntry { EnglishWord = "Organizing data, Making template", HungarianTranslation = "Adatok rendezése, sablon készítése" },
                new DictionaryEntry { EnglishWord = "Other Projects", HungarianTranslation = "Más projekt" },
                new DictionaryEntry { EnglishWord = "Miscellaneous", HungarianTranslation = "Egyéb" },
                new DictionaryEntry { EnglishWord = "P&L preparation", HungarianTranslation = "P&L készítés" },
                new DictionaryEntry { EnglishWord = "Partner communication", HungarianTranslation = "Partner kommunikáció" },
                new DictionaryEntry { EnglishWord = "Payment Issues", HungarianTranslation = "Kifizetési kérdések" },
                new DictionaryEntry { EnglishWord = "Payment Method", HungarianTranslation = "Fizetési mód" },
                new DictionaryEntry { EnglishWord = "People Development", HungarianTranslation = "munkavállalói fejlesztés" },
                new DictionaryEntry { EnglishWord = "People management", HungarianTranslation = "Munkavállaló kezelése" },
                new DictionaryEntry { EnglishWord = "Performance tracking", HungarianTranslation = "Teljesítmény nyomon követése" },
                new DictionaryEntry { EnglishWord = "PH Support", HungarianTranslation = "PH támogatás" },
                new DictionaryEntry { EnglishWord = "Phone Number", HungarianTranslation = "Telefonszám" },
                new DictionaryEntry { EnglishWord = "Phone number isn't correct.", HungarianTranslation = "A telefonszám nem megfelelő." },
                new DictionaryEntry { EnglishWord = "Pitching", HungarianTranslation = "Előadás (Pitch)" },
                new DictionaryEntry { EnglishWord = "Planning workload", HungarianTranslation = "Munkaszervezés" },
                new DictionaryEntry { EnglishWord = "Please select", HungarianTranslation = "Kérem válasszon" },
                new DictionaryEntry { EnglishWord = "Post advertisement", HungarianTranslation = "Hirdetésfeladás" },
                new DictionaryEntry { EnglishWord = "Preferred Language", HungarianTranslation = "Nyelvválasztás" },
                new DictionaryEntry { EnglishWord = "Preparation for meetings", HungarianTranslation = "Megbeszélésre való felkészülés" },
                new DictionaryEntry { EnglishWord = "Prepare monthly Reports", HungarianTranslation = "Havi riportok elkészítése" },
                new DictionaryEntry { EnglishWord = "Prepare Weekly Reports", HungarianTranslation = "Heti riportok elkészítése" },
                new DictionaryEntry { EnglishWord = "Previous", HungarianTranslation = "Előző" },
                new DictionaryEntry { EnglishWord = "Pricing Requests", HungarianTranslation = "Árazás" },
                new DictionaryEntry { EnglishWord = "Process control, review", HungarianTranslation = "Folyamatirányítás, felülvizsgálat" },
                new DictionaryEntry { EnglishWord = "Process improvement", HungarianTranslation = "Folyamatfejlesztés" },
                new DictionaryEntry { EnglishWord = "Profile", HungarianTranslation = "Profil" },
                new DictionaryEntry { EnglishWord = "Project design", HungarianTranslation = "Projekt dizájn" },
                new DictionaryEntry { EnglishWord = "Project review with ops/PM", HungarianTranslation = "Projekt felülvizsgálata ops/PM" },
                new DictionaryEntry { EnglishWord = "Project Setup", HungarianTranslation = "Projekt felállítása" },
                new DictionaryEntry { EnglishWord = "Prepare Guideline", HungarianTranslation = "Útmutató" },
                new DictionaryEntry { EnglishWord = "Briefing", HungarianTranslation = "ájékoztató előkészítése" },
                new DictionaryEntry { EnglishWord = "Providing training", HungarianTranslation = "Képzés tartása" },
                new DictionaryEntry { EnglishWord = "PTO", HungarianTranslation = "PTO" },
                new DictionaryEntry { EnglishWord = "Quality check (Second Line Editing)", HungarianTranslation = "Minőségellenőrzés (2. szintű)" },
                new DictionaryEntry { EnglishWord = "Receiving training", HungarianTranslation = "Tréningen való részvétel" },
                new DictionaryEntry { EnglishWord = "Recruitment", HungarianTranslation = "Toborzás" },
                new DictionaryEntry { EnglishWord = "Report automation", HungarianTranslation = "Jelentés automatizálás" },
                new DictionaryEntry { EnglishWord = "Reporting", HungarianTranslation = "Jelentés" },
                new DictionaryEntry { EnglishWord = "Status Tracking", HungarianTranslation = "állapotkövetés" },
                new DictionaryEntry { EnglishWord = "Follow up", HungarianTranslation = "nyomon követés" },
                new DictionaryEntry { EnglishWord = "Reset Caspian Password", HungarianTranslation = "Caspian Jelszó Visszaállítása" },
                new DictionaryEntry { EnglishWord = "Revenue Confirmation", HungarianTranslation = "Bevétel megerősítése" },
                new DictionaryEntry { EnglishWord = "Review questionnaire", HungarianTranslation = "Kérdőív ellenőrzés" },
                new DictionaryEntry { EnglishWord = "Shopper guideline", HungarianTranslation = "Vásárlói útmutató" },
                new DictionaryEntry { EnglishWord = "Rework - Analyst", HungarianTranslation = "Újrafeldolgozás - Elemző" },
                new DictionaryEntry { EnglishWord = "Rework - Client", HungarianTranslation = "Újrafeldolgozás - Ügyfél" },
                new DictionaryEntry { EnglishWord = "Rework - KAM", HungarianTranslation = "Újrafeldolgozás - KAM" },
                new DictionaryEntry { EnglishWord = "RM Supervisor", HungarianTranslation = "RM Csoportvezető" },
                new DictionaryEntry { EnglishWord = "Roles", HungarianTranslation = "Jogok" },
                new DictionaryEntry { EnglishWord = "Rulez", HungarianTranslation = "Szabályok" },
                new DictionaryEntry { EnglishWord = "Sales to Ops Transition", HungarianTranslation = "Sales to Ops Transition" },
                new DictionaryEntry { EnglishWord = "Save", HungarianTranslation = "Mentés" },
                new DictionaryEntry { EnglishWord = "Save Comment", HungarianTranslation = "Megjegyzés mentése" },
                new DictionaryEntry { EnglishWord = "Save Fee", HungarianTranslation = "Díj mentése" },
                new DictionaryEntry { EnglishWord = "Scheduling", HungarianTranslation = "Ütemezés" },
                new DictionaryEntry { EnglishWord = "Search", HungarianTranslation = "Keresés" },
                new DictionaryEntry { EnglishWord = "Select", HungarianTranslation = "Válasz" },
                new DictionaryEntry { EnglishWord = "Select Agency", HungarianTranslation = "Ügynökség kiválasztása" },
                new DictionaryEntry { EnglishWord = "Select task", HungarianTranslation = "Feladat kiválasztása" },
                new DictionaryEntry { EnglishWord = "Self Assigned", HungarianTranslation = "Önmagához rendelt" },
                new DictionaryEntry { EnglishWord = "SG support", HungarianTranslation = "SG támogatás" },
                new DictionaryEntry { EnglishWord = "Social Media", HungarianTranslation = "Social Media" },
                new DictionaryEntry { EnglishWord = "Spent hours", HungarianTranslation = "Óraszám" },
                new DictionaryEntry { EnglishWord = "Start", HungarianTranslation = "Kezdés" },
                new DictionaryEntry { EnglishWord = "Start - End", HungarianTranslation = "Kezdés - Vég" },
                new DictionaryEntry { EnglishWord = "Start date:", HungarianTranslation = "Kezdő dátum:" },
                new DictionaryEntry { EnglishWord = "Start time:", HungarianTranslation = "Kezdő idő:" },
                new DictionaryEntry { EnglishWord = "Sunday", HungarianTranslation = "Vasárnap" },
                new DictionaryEntry { EnglishWord = "Supervisor Name", HungarianTranslation = "Csoportvezető neve" },
                new DictionaryEntry { EnglishWord = "Support", HungarianTranslation = "Támogatás" },
                new DictionaryEntry { EnglishWord = "Surfermerchants", HungarianTranslation = "Surfermerchants" },
                new DictionaryEntry { EnglishWord = "Survey", HungarianTranslation = "kérdőív" },
                new DictionaryEntry { EnglishWord = "Switch to", HungarianTranslation = "Válts erre" },
                new DictionaryEntry { EnglishWord = "Task", HungarianTranslation = "Feladat" },
                new DictionaryEntry { EnglishWord = "Task:", HungarianTranslation = "Feladat:" },
                new DictionaryEntry { EnglishWord = "The right format is 'hh:mm'", HungarianTranslation = "A megfelelő formátum: 'óó: mm'" },
                new DictionaryEntry { EnglishWord = "This field can't be empty!", HungarianTranslation = "Ez a mező nem lehet üres!" },
                new DictionaryEntry { EnglishWord = "Thursday", HungarianTranslation = "Csütörtök" },
                new DictionaryEntry { EnglishWord = "Tier 1", HungarianTranslation = "Tier 1" },
                new DictionaryEntry { EnglishWord = "Tier 2", HungarianTranslation = "Tier 2" },
                new DictionaryEntry { EnglishWord = "Timesheet", HungarianTranslation = "Jelenléti ív" },
                new DictionaryEntry { EnglishWord = "Timesheetuser Username", HungarianTranslation = "Jelenléti ív felhasználó felhasználónéve" },
                new DictionaryEntry { EnglishWord = "Today", HungarianTranslation = "Ma" },
                new DictionaryEntry { EnglishWord = "Tracker handling", HungarianTranslation = "Tracker kezelés" },
                new DictionaryEntry { EnglishWord = "Training - Self", HungarianTranslation = "Tréning - saját" },
                new DictionaryEntry { EnglishWord = "coaching team member", HungarianTranslation = "csapat társ" },
                new DictionaryEntry { EnglishWord = "external", HungarianTranslation = "külsős" },
                new DictionaryEntry { EnglishWord = "Training", HungarianTranslation = "Tréning" },
                new DictionaryEntry { EnglishWord = "Briefing Shopper", HungarianTranslation = "Próbavásárló képzés" },
                new DictionaryEntry { EnglishWord = "coaching team member", HungarianTranslation = "csapat társ" },
                new DictionaryEntry { EnglishWord = "Translation", HungarianTranslation = "Fordítás" },
                new DictionaryEntry { EnglishWord = "Translation of Guidelines, other documents, etc.", HungarianTranslation = "Iránymutatások, egyéb dokumentumok fordítása" },
                new DictionaryEntry { EnglishWord = "Tuesday", HungarianTranslation = "Kedd" },
                new DictionaryEntry { EnglishWord = "Type your comment here...", HungarianTranslation = "Megjegyzés..." },
                new DictionaryEntry { EnglishWord = "Type to search...", HungarianTranslation = "Keresés megadás..." },
                new DictionaryEntry { EnglishWord = "US support", HungarianTranslation = "US támogatás" },
                new DictionaryEntry { EnglishWord = "Use the arrow keys on the keyboard (Up, Down) to change the selection. Columns can be resized by the oblique lines in the header, rows can be resized by the oblique lines in the first cell.", HungarianTranslation = "A kiválasztás módosításához használja a billentyűzet nyílgombjait (Fel, Le). Az oszlopok átméretezhetők a fejléc ferde vonalaival, a sorok pedig az első cellában lévő ferde vonalakkal." },
                new DictionaryEntry { EnglishWord = "User Id", HungarianTranslation = "Felhasználó azonosító" },
                new DictionaryEntry { EnglishWord = "User Name", HungarianTranslation = "Felhasználónév" },
                new DictionaryEntry { EnglishWord = "User Type", HungarianTranslation = "Felhasználó típus" },
                new DictionaryEntry { EnglishWord = "User With Agency", HungarianTranslation = "Ügynökség felhasználója" },
                new DictionaryEntry { EnglishWord = "VAT", HungarianTranslation = "ÁFA" },
                new DictionaryEntry { EnglishWord = "GST tax preparation and filing", HungarianTranslation = "GST adó előkészítése és benyújtása" },
                new DictionaryEntry { EnglishWord = "Vendor", HungarianTranslation = "Szolgáltató" },
                new DictionaryEntry { EnglishWord = "Vendor Fees", HungarianTranslation = "Szolgáltatói díjak" },
                new DictionaryEntry { EnglishWord = "Vendor Id", HungarianTranslation = "Szolgáltatói azonosító" },
                new DictionaryEntry { EnglishWord = "Vendor Invoicing", HungarianTranslation = "Szolgáltatói számlázás" },
                new DictionaryEntry { EnglishWord = "Vendor Name", HungarianTranslation = "Szolgáltató neve" },
                new DictionaryEntry { EnglishWord = "Vendor payments", HungarianTranslation = "Szolgáltatói kifizetések" },
                new DictionaryEntry { EnglishWord = "Wave", HungarianTranslation = "Wave" },
                new DictionaryEntry { EnglishWord = "Wednesday", HungarianTranslation = "Szerda" },
                new DictionaryEntry { EnglishWord = "Week Days", HungarianTranslation = "Hétköznapok" },
                new DictionaryEntry { EnglishWord = "Western Union Address", HungarianTranslation = "Western Union cím" },
                new DictionaryEntry { EnglishWord = "Whole Week", HungarianTranslation = "Teljes hét" },
                new DictionaryEntry { EnglishWord = "Yes", HungarianTranslation = "Igen" }
            };

            // Add translations to the database context
            _context.Dictionary.AddRange(translations);

            // Save changes to database
            _context.SaveChanges();
        }
    }
}
